export const cosmetics = [
	{
		id: 1,
		category: "hair",
		subcategory: "hair-shampoo",
		name: "Szampon normalizujący",
		title: "Szampon normalizujący do włosów przetłuszczających się",
		description: "Szampon powstały na bazie substancji myjących pochodzenia naturalnego. Wyciągi roślinne i ziołowe m.in. z pokrzywy, tymianku, łopianu i jałowca regulują pracę gruczołów łojowych oraz wzmacniają cebulki włosów. Zawartość mentolu odświeża i tonizuje, pantenol nawilża i nadaje połysk. Szampon doskonale oczyszcza włosy z zanieczyszczeń oraz pozostałości po środkach do stylizacji pozostawiając delikatny, orzeźwiający zapach.",
		image: require("./images/cosmetics/cos_12.jpg"),
		amount: 18,
		price: 39.90,
		capacity: "500ml"
	},
	{
		id: 2,
		category: "hair",
		subcategory: "hair-shampoo",
		name: "Szampon regenerujący",
		title: "Szampon intensywnie regenerujący z biotyną i keratyną",
		description: "Zawarta biotyna (witamina B7) przywraca siłę zniszczonym włosom, niweluje ich łamliwość i zmniejsza wypadanie. Wspólnie z keratyną wzmacnia i regeneruje łuskę włosa oraz uzupełnia niedobór naturalnych składników. Pantenol doskonale nawilża włosy, chroni przed uszkodzeniami, dodaje im objętości. Pobudzająca arginina oraz ekstrakty z lnu i żeń-szenia stymulują wzrost włosów.",
		image: require("./images/cosmetics/cos_11.jpg"),
		amount: 26,
		price: 39.90,
		capacity: "500ml"
	},
	{
		id: 3,
		category: "hair",
		subcategory: "hair-shampoo",
		name: "Szampon odbudowujący",
		title: "Szampon odbudowujący do włosów zniszczonych, suchych i farbowanych",
		description: "Formuła zawiera łagodne, ale skuteczne środki myjące pochodzenia roślinnego. Niezwykle bogaty skład współtworzą ekstrakty z cytryny i lnu, szlachetny olej babassu, proteiny jedwabiu oraz keratyna - znane ze swoich dobroczynnych właściwości. W celu wzmocnienia pielęgnacji włosów zniszczonych i farbowanych formułę uzupełniono o filtr UV, witaminę F oraz prowitaminę B5. Szampon skutecznie myje włosy i skórę głowy pozostawiając je czyste i świeże. ",
		image: require("./images/cosmetics/cos_15.jpg"),
		amount: 40,
		price: 45.90,
		capacity: "500ml"
	},
	{
		id: 4,
		category: "hair",
		subcategory: "hair-shampoo",
		name: "Szampon wzmacniający",
		title: "Szampon intensywnie wzmacniający do pielęgnacji włosów słabych, łamliwych i skłonnych do wypadania",
		description: "Receptura oparta o starannie dobrane substancje myjące pochodzenia naturalnego. Hydrolizowane proteiny oraz aminokwasy pszenicy i soi tworzą na powierzchni włosa delikatny biofilm, zatrzymują wilgoć, wzmacniają i chronią przed negatywnym działaniem czynników zewnętrznych. Dodatek kofeiny, argininy oraz ekstraktu z guarany i bajkaliny stymuluje mikrokrążenie skórne pobudzając włosy do wzrostu.",
		image: require("./images/cosmetics/cos_11.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "500ml"
	},
	{
		id: 5,
		category: "hair",
		subcategory: "hair-shampoo",
		name: "Szampon wygładzający",
		title: "Szampon intensywnie wygładzający z jedwabiem do włosów słabych, szorstkich i zniszczonych",
		description: "Zawiera 97,00 % składników pochodzenia naturalnego. Zawarty w szamponie jedwab otula powierzchnię włosa, utrzymuje w nim wilgoć i chroni przed negatywnymi czynnikami środowiska. Kwasy omega i inulina sprawiają, że włosy są gładkie i miłe w dotyku. Wyciągi roślinne z lnu i cytryny stymulują procesy regeneracji, wzmacniają oraz działają przeciwutleniająco. Receptura uzupełniona o filtr UV doskonale sprawdzi się w przypadku włosów farbowanych, narażonych na blaknięcie koloru pod wpływem słońca.",
		image: require("./images/cosmetics/cos_12.jpg"),
		amount: 15,
		price: 39.90,
		capacity: "500ml"
	},
	{
		id: 6,
		category: "hair",
		subcategory: "hair-conditioner",
		name: "Organic Hair Biotin",
		title: "Odżywka regenerująca do włosów suchych i zniszczonych",
		description: "Odżywka intensywnie regenerująca zawiera biotynę (witaminę B7), która przywraca siłę zniszczonym włosom, zwiększa elastyczność i zmniejsza ich wypadanie. Dodatek regenerującej keratyny oraz nawilżającego pantenolu pielęgnuje włosy od nasady po same końce. Pobudzająca arginina i ekstrakty z lnu i żeń-szenia wzmacniają włosy oraz stymulują ich wzrost.",
		image: require("./images/cosmetics/cos_19.jpg"),
		amount: 20,
		price: 29.90,
		capacity: "200ml"
	},
	{
		id: 7,
		category: "hair",
		subcategory: "hair-conditioner",
		name: "Organic Hair Keratin",
		title: "Odżywka odbudowująca do włosów puszących się, suchych i kręconych oraz osłabionych podczas zabiegów fryzjerskich",
		description: "Intensywnie odbudowująca odżywka z keratyną przeznaczona do pielęgnacji włosów puszących się, suchych i kręconych oraz osłabionych podczas zabiegów fryzjerskich. Zawarta w jej składzie keratyna wypełnia ubytki w łusce włosa, wzmacnia, regeneruje, zapobiega łamaniu, rozdwajaniu i chroni przed szkodliwym działaniem czynników zewnętrznych. Naturalne masło shea oraz oleje: jojoba i macadamia zmiękczają i nadają gładkości. Ekstrakty z kiełków soi i pszenicy, prowitamina B5 i witamina E nawilżają oraz działają przeciwutleniająco. Dodatek składników aktywnych pomaga rozczesać włosy, niweluje elektryzowanie oraz puszenie się.",
		image: require("./images/cosmetics/cos_9.jpg"),
		amount: 12,
		price: 44.90,
		capacity: "300ml"
	},
	{
		id: 8,
		category: "hair",
		subcategory: "hair-conditioner",
		name: "Organic Hair Protein",
		title: "Odżywka wzmacniająca Do włosów słabych, łamliwych i skłonnych do wypadania. ",
		description: "Odżywka intensywnie wzmacniająca stworzona w oparciu o naturalne składniki aktywne: masło shea oraz oleje makadamia i babassu. Hydrolizowane proteiny oraz aminokwasy pszenicy i soi tworzą na powierzchni włosa delikatny biofilm, zatrzymują wilgoć, wzmacniają, uelastyczniają oraz chronią przed negatywnym działaniem czynników zewnętrznych. Kofeina oraz wyciągi z guarany i bajkaliny wzmacniają oraz pobudzają włosy do wzrostu. Odżywka stanowi idealne uzupełnienie szamponu do włosów z serii Protein.",
		image: require("./images/cosmetics/cos_19.jpg"),
		amount: 50,
		price: 39.90,
		capacity: "300ml"
	},
	{
		id: 9,
		category: "hair",
		subcategory: "hair-conditioner",
		name: "Organic Hair Keratin Spray",
		title: "Keratynowy spray do włosów suchych i zniszczonych",
		description: "Keratynowy spray do włosów bez spłukiwania.Keratyna wzmacnia i regeneruje łuskę włosa oraz uzupełnia niedobór naturalnych składników budulcowych. Ekstrakty z zarodków soi, pszenicy oraz wyciąg z henny i bajkaliny stymuluje wzrost włosów, poprawia ich gęstość, zmniejsza wypadanie oraz przywraca zdrowy i mocny wygląd.",
		image: require("./images/cosmetics/cos_9.jpg"),
		amount: 50,
		price: 29.90,
		capacity: "100ml"
	},
	{
		id: 10,
		category: "hair",
		subcategory: "hair-conditioner",
		name: "Organic Hair Argan",
		title: "Odżywka do włosów z olejem arganowym do włosów suchych, puszących się",
		description: "Odżywka na bazie składników pochodzenia naturalnego do włosów suchych, puszących się i poddawanych zabiegom fryzjerskim. Bogata formuła ułatwia rozczesywanie i ogranicza elektryzowanie się włosów. Wszechstronne działanie zapewniają: cenne oleje roślinne nie obciążające włosów, czyli olej arganowy i masło shea, proteiny pszenicy, keratyny i jedwabiu oraz aktywne wyciągi roślinne (z rozmarynu, rumianku, arniki, jasnoty, paków sosny, rukwi wodnej, łopianu, cytryny, bluszczu, nagietka, nasturcji oraz szałwii).",
		image: require("./images/cosmetics/cos_19.jpg"),
		amount: 100,
		price: 39.90,
		capacity: "300ml"
	},
	{
		id: 11,
		category: "hair",
		subcategory: "hair-mask",
		name: "Organic Hair Silk",
		title: "Maska wygładzająca do włosów słabych, szorstkich i zniszczonych.",
		description: "Intensywnie wygładzająca maska do włosów z jedwabiem, olejem jojoba, olejem rycynowym, masłem shea oraz inuliną, które zmiękczają, ułatwiają rozczesywanie oraz przeciwdziałają elektryzowaniu się włosów. Zawarty w masce jedwab otula włos, utrzymuje w nim wilgoć oraz działa jak tarcza ochronna przed czynnikami zewnętrznymi. Naturalne wyciągi roślinne z lnu i cytryny stymulują procesy regeneracji, wzmacniają oraz działają przeciwutleniająco, a filtr UV sprawia, że maska doskonale sprawdzi się w przypadku włosów farbowanych.",
		image: require("./images/cosmetics/cos_9.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "200ml"
	},
	{
		id: 12,
		category: "hair",
		subcategory: "hair-mask",
		name: "Organic Repair Hair Mask",
		title: "Maska regenerująca do włosów silnie zniszczonych zabiegami fryzjerskimi.",
		description: "Ta luksusowa maska regenerująca ​​do włosów wykonana jest z organicznego olejku z awokado i ekologicznego miodu, które wzmacniają włosy od korzeni po same końce, poprawiając ich strukturę. W ten sposób Twoje włosy będą bardziej miękkie, a także o wiele bardziej błyszczące.",
		image: require("./images/cosmetics/cos_19.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "200ml"
	},
	{
		id: 13,
		category: "hair",
		subcategory: "hair-mask",
		name: "Ginger Hair Mask",
		title: "Maska wzmacniająca do włosów wszystkich rodzajów włosów",
		description: "Specjalnymi składnikami ajurwedyjskimi wybranymi do tego produktu są Methi, Ginger i Brahmi, które mają działanie wzmacniające na łamliwe włosy i, w synergii z białkami pszenicy, nawilżają włosy i pomagają uczynić je zdrowymi i silnymi.Ponadto zawiera masło shea i olej lniany, bogate w niezbędne nienasycone kwasy tłuszczowe, białka i witaminy, które odżywiają i naprawiają włókna włosów.",
		image: require("./images/cosmetics/cos_9.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "200ml"
	},
	{
		id: 14,
		category: "hair",
		subcategory: "hair-mask",
		name: "Black Moroccan Hair Mask",
		title: "Marokańska maska do włosów przeciw wypadaniu włosów",
		description: "maska regenerująca ​​do włosów wykonana jest z organicznego olejku z awokado, które wzmacniają włosy od korzeni po same końce, poprawiając ich strukturę. W ten sposób Twoje włosy będą bardziej miękkie oraz błyszczące.",
		image: require("./images/cosmetics/cos_19.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "200ml"
	},
	{
		id: 15,
		category: "face",
		subcategory: "face-wash",
		name: "Argan Foaming Wasch",
		title: "Arganowa pianka do twarzy, rąk i ciała",
		description: "Lekka, aromatyczna pianka do mycia twarzy, rąk i ciała na bazie delikatnych środków myjących pochodzenia naturalnego. Łagodnie, lecz skutecznie oczyszcza skórę, a dzięki zawartości oleju arganowego, roślinnej gliceryny oraz ekstraktów z 12 ziół odżywia i pielęgnuje skórę suchą, bardzo suchą i delikatną. Polecana do codziennego stosowania jako alternatywa dla mydeł w płynie.",
		image: require("./images/cosmetics/cos_19.jpg"),
		amount: 30,
		price: 29.90,
		capacity: "175ml"
	},
	{
		id: 16,
		category: "face",
		subcategory: "face-wash",
		name: "Hyaluronate Foaming Wasch",
		title: "Pianka do twarzy, rąk i ciała",
		description: "Lekka, aromatyczna pianka do mycia twarzy, rąk i ciała na bazie delikatnych środków myjących pochodzenia naturalnego. Łagodnie, lecz skutecznie oczyszcza skórę, a dzięki zawartości kwasu hialuronowego i roślinnej gliceryny odżywia skórę suchą, delikatną, pozbawioną elastyczności. Pianka polecana jest do codziennego stosowania jako alternatywa dla mydeł w płynie.",
		image: require("./images/cosmetics/cos_19.jpg"),
		amount: 30,
		price: 29.90,
		capacity: "175ml"
	},
	{
		id: 17,
		category: "face",
		subcategory: "face-cream-day",
		name: "Argan Face Cream",
		title: "Krem do twarzy z olejem arganowym",
		description: "Nawilżający krem przeciwstarzeniowy do twarzy ze szlachetnym olejem arganowym nazywanym „złotem Maroka”. Starannie dobrane składniki poprawiają elastyczność i sprężystość skóry, zmniejszając widoczność zmarszczek. Regularnie stosowany, aksamitny krem opóźnia procesy starzenia i niweluje oznaki zmęczenia, nadając cerze zdrowy i młodszy wygląd. Naturalne masła shea i kokosowe oraz proteiny pszenicy i jedwabiu wygładzają, poprawiają kondycje skóry oraz pozostawiają ja promienną i pełną blasku.",
		image: require("./images/cosmetics/cos_20.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "50ml"
	},
	{
		id: 18,
		category: "face",
		subcategory: "face-cream-day",
		name: "Bio Detox Face Cream",
		title: "Krem do twarzy rzeznaczony do skóry z tendencją do występowania niedoskonałości i trądziku, do cery mieszanej oraz nadmiernie wydzielającej sebum",
		description: "Aksamitny krem wzbogacony o aktywny kompleks ekstraktów z bazylii, rozmarynu, kasztanowca oraz alg morskich i jabłek głęboko odżywia skórę twarzy, pozostawiając ją naturalnie piękną i promienną. Lekka formuła kremu nie pozostawia uczucia tłustości, a zawarty w nim kaolin działa delikatnie matująco, wchłaniając nadmiar sebum. Zawiera kwas salicylowy oraz origanol – najskuteczniejszą frakcję olejku z drzewa herbacianego, dzięki czemu kompleksowo pielęgnuje skórę trądzikową, z niedoskonałościami, podatną na stany zapalne.",
		image: require("./images/cosmetics/cos_20.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "50ml"
	},
	{
		id: 19,
		category: "face",
		subcategory: "face-cream-night",
		name: "Vitamin C Brightening Face Cream",
		title: "Krem do twarzy na noc przeznaczony do skóry suchej, skłonnej do zaczerwienień i przebarwień, pozbawionej blasku",
		description: "Odżywczy krem do twarzy z dodatkiem witaminy C stworzony z myślą o skórze skłonnej do zaczerwienień i przebarwień. Naturalne oleje, m.in. masło shea, wzbogacone o ekstrakty z szałwii, cytryny, zielonej herbaty, jagód goji oraz witaminy B5 i E gwarantują, że dzięki regularnemu stosowaniu krem rozjaśnia, nawilża, ujędrnia, poprawia kondycję skóry oraz dogłębnie ją odżywia. Krem idealnie sprawdzi się w pielęgnacji przeciwstarzeniowej, sprawiając, że skóra nabierze witalności i naturalnego blasku.",
		image: require("./images/cosmetics/cos_20.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "50ml"
	},
	{
		id: 20,
		category: "face",
		subcategory: "face-cream-night",
		name: "Anti-Age Face Cream",
		title: "Krem do twarzy na noc przeznaczony do skóry suchej, pozbawionej jędrności, z przebarwieniami",
		description: "Lekki i aksamitny krem do twarzy z witaminą C do skóry skłonnej do zaczerwienień i przebarwień. Powstał na bazie surowców naturalnych: masła shea, oleju z pestek winogron, soku z aloesu, ekstraktu z szałwii i zielonej herbaty, a także witamin C, B5, E i alantoiny. Regularne stosowanie kremu opóźnia procesy starzenia oraz powoduje widoczne spłycenie zmarszczek. Następuje poprawa nawilżenia skóry, przez co odzyskuje ona blask oraz zdrowy wygląd.",
		image: require("./images/cosmetics/cos_20.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "50ml"
	},
	{
		id: 21,
		category: "body",
		subcategory: "body-wash",
		name: "Algae Shower Gel",
		title: "Żel pod prysznic z ekstraktem z alg morskich",
		description: "Naturalny i odżywczy żel do kąpieli i pod prysznic doskonale pielęgnuje skórę pozostawiając ją jedwabiście gładką, nie powodując podrażnień. Prowitamina B5 oraz gliceryna roślinna doskonale odżywia skórę podczas kąpieli. Ekstrakt z alg morskich: laminarii, nori, morszczynu i spiruliny pomaga zachować właściwy poziom nawilżenia skóry. Świeży, morski aromat wypełni całą łazienkę.",
		image: require("./images/cosmetics/cos_15.jpg"),
		amount: 30,
		price: 24.90,
		capacity: "250ml"
	},
	{
		id: 29,
		category: "body",
		subcategory: "body-wash",
		name: "Shea Shower Gel",
		title: "Żel pod prysznic z masłem shea",
		description: "Żel do kąpieli i pod prysznic o bogatej, kremowej formule z odżywczym masłem shea, mleczkiem migdałowym z Hiszpanii, nawilżającą prowitaminą B5 oraz antyoksydacyjną witaminą E. Doskonale oczyszcza skórę całego ciała oraz pozostawia ją aksamitnie delikatną i odświeżoną.",
		image: require("./images/cosmetics/cos_15.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "500ml"
	},
	{
		id: 22,
		category: "body",
		subcategory: "body-wash",
		name: "Grapefruit Shower Gel",
		title: "Żel pod prysznic z ekstraktem z grejpfruita",
		description: "Naturalny i odżywczy żel do kąpieli i pod prysznic doskonale pielęgnuje skórę pozostawiając ją jedwabiście gładką, nie powodując podrażnień. Prowitamina B5 oraz gliceryna roślinna doskonale odżywia skórę podczas kąpieli. Ekstrakt z grejpfruta zwalcza wolne rodniki, rewitalizuje skórę, a obecność kwasów owocowych stymuluje skórę do regeneracji. Świeży, cytrusowy aromat wypełni całą łazienkę.",
		image: require("./images/cosmetics/cos_15.jpg"),
		amount: 30,
		price: 39.90,
		capacity: "500ml"
	},
	{
		id: 23,
		category: "body",
		subcategory: "body-peeling",
		name: "Green Tea Body Scrub",
		title: "Peeling do ciała z ekstraktem z zielonej herbaty",
		description: "Masaż z jego udziałem usuwa martwe komórki naskórka, stymuluje mikrokrążenie, oczyszcza oraz wygładza skórę. Wysoka zawartość gliceryny wpływa na prawidłowy poziom nawilżenia. Zielona herbata działa przeciwstarzeniowo i chroni przed wolnymi rodnikami. Idealnie przygotowuje skórę do dalszych zabiegów pielęgnacyjnych.",
		image: require("./images/cosmetics/cos_5.jpg"),
		amount: 30,
		price: 24.90,
		capacity: "260g"
	},
	{
		id: 24,
		category: "body",
		subcategory: "body-peeling",
		name: "Manuka Body Scrub",
		title: "Peeling do ciała z pochodzącym z Nowej Zelandii miodem Manuka",
		description: "Peeling do ciała z dodatkiem kryształków soli z Morza Martwego, witaminą E oraz pochodzącym z Nowej Zelandii miodem Manuka. Masaż z jego udziałem usuwa martwe komórki naskórka, stymuluje mikrokrążenie, oczyszcza oraz wygładza skórę. Wysoka zawartość gliceryny wpływa na prawidłowy poziom nawilżenia. Miód Manuka bogaty jest w dużą ilość substancji odżywczych, wspomaga regenerację skóry. Idealnie przygotowuje skórę do dalszych zabiegów pielęgnacyjnych.",
		image: require("./images/cosmetics/cos_5.jpg"),
		amount: 30,
		price: 24.90,
		capacity: "260g"
	},
	{
		id: 25,
		category: "body",
		subcategory: "body-peeling",
		name: "Plum & Fig Body Scrub",
		title: "Peeling do ciała z olejem z pestek śliwek",
		description: "Peeling do ciała z dodatkiem kryształków soli z Morza Martwego, witaminą E oraz olejem z pestek śliwek. Masaż z jego udziałem usuwa martwe komórki naskórka, stymuluje mikrokrążenie, oczyszcza oraz wygładza skórę. Wysoka zawartość gliceryny wpływa na prawidłowy poziom nawilżenia. Olej z pestek śliwek zmiękcza i wygładza skórę. Idealnie przygotowuje skórę do dalszych zabiegów pielęgnacyjnych.",
		image: require("./images/cosmetics/cos_5.jpg"),
		amount: 30,
		price: 24.90,
		capacity: "260g"
	},
	{
		id: 26,
		category: "body",
		subcategory: "body-balm",
		name: "Sweet Mango Body Butter",
		title: "Masło do ciała z ekstraktem z mango",
		description: "Odżywcze masło do ciała powstałe na bazie naturalnych składników: oleju avocado, masła shea oraz ekstraktu z soczystego i słonecznego mango. Innowacyjna naturalna formuła sprawia, że doskonale się wchłania, pozostawiając lekką, ochronną warstwę. Olej, alantoina, pantenol, skwalan i witamina E przywracają skórze komfort i gładkość. Ekstrakt z mango bogaty jest w dużą ilość witamin, które doskonale odżywiają skórę. Regularnie stosowane zapobiega utracie wody, ograniczając tym samym procesy starzenia się skóry.",
		image: require("./images/cosmetics/cos_9.jpg"),
		amount: 30,
		price: 33.90,
		capacity: "200ml"
	},
	{
		id: 27,
		category: "body",
		subcategory: "body-balm",
		name: "Tuberose & Yuzu Body Butter",
		title: "Masło do ciała z ekstraktem z hibiskusa",
		description: "Kremowe masło do ciała powstałe na bazie naturalnych składników: oleju avocado, masła shea oraz ekstraktu z hibiskusa. Masło doskonale się wchłania, odżywia i pielęgnuje pozostawiając lekką, ochronną warstwę. Zaawansowana formuła z alantoiną, pantenolem, skwalanem i witaminą E przywraca skórze komfort i gładkość. Ekstrakt z kwiatu hibiskusa chroni przed wolnymi rodnikami i działa ujędrniająco. Regularnie stosowane zapobiega utracie wody, ograniczając tym samym procesy starzenia się skóry.",
		image: require("./images/cosmetics/cos_9.jpg"),
		amount: 30,
		price: 33.90,
		capacity: "200ml"
	},
	{
		id: 28,
		category: "body",
		subcategory: "body-balm",
		name: "Chocolate Brownie Body Lotion",
		title: "Balsam do ciała z masłem kakaowym",
		description: "Aksamitny balsam do ciała z masłem kakaowym, kakao oraz ekstraktem z kakaowca. Naturalne, sprawdzone składniki wzbogacone o alantoinę, prowitaminę B5 oraz witaminę E dogłębnie odżywiają oraz pielęgnują przesuszoną skórę, nadając jej zdrowy wygląd. Masło kakaowe natłuszcza, uelastycznia oraz zmiękcza skórę. Stosowanie balsamu zapobiega utracie wody z naskórka oraz otula ciało kuszącym czekoladowym zapachem.",
		image: require("./images/cosmetics/cos_9.jpg"),
		amount: 30,
		price: 33.90,
		capacity: "200ml"
	},


]